### PR TITLE
don't return memory allocated on the stack

### LINKED ISSUE #189: commit a3ba81765daeffaaa2e9e59d49d49ae4438b1b59 broke client/server sample
```
$ build/dbg/samples/client foo
client: failed to read from region -559038737 0-0x3: Invalid argument
devinfo: flags 0, num_regions 0, num_irqs 0
client: could not find migration region
```

### PR DESCRIPTION
**Pull request by tmakatos**
Signed-off-by: Thanos Makatos <thanos.makatos@nutanix.com>

fixes #189

### CODE REVIEW

File: lib/libvfio-user.c [hunk 1]
```diff
@@ -878,8 +878,8 @@ exec_command(vfu_ctx_t *vfu_ctx, struct vfio_user_header *hdr, size_t size,
              bool *free_iovec_data)
```
Comment (swapnili) [inline lib/libvfio-user.c:878]: This function can be simplified. 
e.g Looks like there is no need to pass _iovecs,.

**Review by swapnili — APPROVED** [review]

**Review by jlevon — APPROVED** [review]
This looks OK, but the iovec handling is getting a bit complicated here.
We might want to look at cleaning it up later.
(One approach is to keep a record of every allocation in the vfu_ctx, then just walk through and free that list at the end. But we still have the iovec pointer handling stuff...)

**Comment by tmakatos** [comment]
I agree it's getting a bit complicated, I've deliberately left it like that since we're planning to simplify it once v7 is approved (https://github.com/nutanix/libvfio-user/issues/112).
